### ISSUE TITLE
Call for testing open source setup

### ISSUE THREAD

**Issue by pal1000** [pal1000/Realtek-UAD-generic#27]
Release 6.0.8862.1 includes a development version of open source setup - `setup-dev.cmd` in addition to stable release. 6.0.8863.1 promoted it to stable, but the old version was kept as `setup-legacy.cmd`. The new setup supports deletion of all side by side generic UAD components from driver store at once and implements the necessary backend change to add support for Realtek OEM specific UAD components removal via config file in the near future.

Ping users who contributed code, experienced hiccups with Realtek Audio Console, reported valid bugs or provided good suggestions against setup or who had confirmed conflicting drivers in Windows driver store:
- [ ] @gtumanyan (reason: conflicting drivers in Windows driver store - #26);
- [ ] @AlyoshaVasilieva (reason: conflicting drivers in Windows driver store - #26);
- [x] @akks1981 (reason: bug report - #25);
- [ ] @DooGie666 (reasons: enhancement request - #7, bug report - #24);
- [ ] @lllopo (reason: bug report - #21);
- [ ] @julianxhokaxhiu (reasons: hiccup with Realtek Audio Console due to conflict in Windows driver store - #2, bug report - #17, bug resolution collaborator - #20);
- [ ] @purifiedh2o (reason: code contribution - #18);
- [ ] @suppai (reason: hiccup with Realtek Audio Console due to unknown reasons - #15);
- [ ] @madakab (reason: hiccups with Realtek Audio Console due to missing, conflicting or duplicate drivers in Windows driver store - #6, #12);
- [ ] @Velken (reason:  hiccup with Realtek Audio Console and recurrent conflict in Windows driver store - #5).

**Comment by akks1981** [comment]
Hello, today I did a clean installation of "Windows 10 20H1 19041.1". I had no problems installing the sound drivers with the "setup-dev.cmd"! Thank you for your great work.

**Comment by pal1000** [comment]
Time's up. 6.0.8864.1 removes legacy setup as I got no bug reports.
